/*
 * This source file was generated by the Gradle 'init' task
 */
package org.or.orcompta;

import org.or.orcompta.ui.controls.Controller;
import javafx.application.Application;
import javafx.stage.Stage;




public class App extends Application{
    
    @Override
    public void start(Stage stage) {
        Controller controller = new Controller(stage);
        controller.displayView();        
    }

    public static void main(String[] args) {
        launch();
        
    }
    
}
